#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

#
# 飞书收件箱配置向导（#7）：创建飞书自建应用、开启机器人、开通消息权限、发布，
# 然后把 App ID、App Secret 与你的 open_id 写入用户配置目录：
#   %APPDATA%\sub2obsidian\credentials\feishu.env
# 凭据只存放在这里，绝不进入知识库或任何 git 仓库。可重复运行：回车保留已保存的值。
#
# 用法（Git Bash，在本仓库根目录）：bash scripts/feishu-inbox-setup.sh

TOTAL_STAGES=7

CONFIG_DIR="${APPDATA:?找不到 APPDATA 环境变量：请在 Windows 的 Git Bash 中运行}/sub2obsidian"
if command -v cygpath >/dev/null 2>&1; then CONFIG_DIR="$(cygpath -u "$CONFIG_DIR")"; fi
ENV_FILE="$CONFIG_DIR/credentials/feishu.env"
mkdir -p "$(dirname "$ENV_FILE")"

banner "sub2obsidian 飞书收件箱配置"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "创建飞书自建应用"
say "收件箱是你与一个飞书机器人的私聊。先在飞书开放平台创建一个只给自己用的应用。"
open_url "https://open.feishu.cn/app"
step "用你的飞书账号登录开发者后台。"
step "点击「创建企业自建应用」，名称填「sub2obsidian 收件箱」，描述随意，点击「创建」。"
pause "创建好后按回车继续"

# ── 2 ────────────────────────────────────────────────────────────────────
stage "复制应用凭据"
step "在刚创建的应用里，打开左侧「凭证与基础信息」。"
step "复制 App ID（以 cli_ 开头）。"
ask FEISHU_APP_ID "粘贴 App ID："
while [[ ! "$FEISHU_APP_ID" =~ ^cli_ ]]; do
  warn "App ID 应以 cli_ 开头，请重新复制。"
  ask FEISHU_APP_ID "粘贴 App ID："
done
step "点击 App Secret 旁的显示或复制按钮，复制 App Secret。"
ask_secret FEISHU_APP_SECRET "粘贴 App Secret（输入不显示）："
while [[ -z "$FEISHU_APP_SECRET" ]]; do
  ask_secret FEISHU_APP_SECRET "App Secret 不能为空，请重新粘贴："
done
write_env FEISHU_APP_ID "$FEISHU_APP_ID"
write_env FEISHU_APP_SECRET "$FEISHU_APP_SECRET"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "开启机器人能力"
step "打开左侧「应用能力」→「添加应用能力」。"
step "找到「机器人」，点击「添加」。"
note "有了机器人能力，你才能在飞书里和这个应用私聊。"
pause "添加好后按回车继续"

# ── 4 ────────────────────────────────────────────────────────────────────
stage "开通消息权限"
step "打开左侧「权限管理」，在搜索框输入 im:message。"
step "开通「获取与发送单聊、群组消息」（im:message）。"
note "读取与机器人私聊的消息要用它；首次 sync 时机器人给你发一条「收件箱已连接」也要用它。"
note "不需要开通事件订阅或回调地址：sync 时主动拉取消息。"
pause "开通好后按回车继续"

# ── 5 ────────────────────────────────────────────────────────────────────
stage "发布应用"
step "打开左侧「版本管理与发布」，点击「创建版本」。"
step "版本号填 1.0.0；「可用范围」务必包含你自己。"
step "保存后点击「申请线上发布」。"
note "需要审核时，由飞书组织的管理员通过；你自己是管理员就自己通过。"
note "权限或可用范围以后有改动，都要再创建一个版本并发布才生效。"
pause "应用显示为「已发布」后按回车继续"

# ── 6 ────────────────────────────────────────────────────────────────────
stage "获取你的 open_id"
say "机器人要知道私聊的对象是你。open_id 因应用而异，所以要在这个应用下取。"
open_url "https://open.feishu.cn/api-explorer"
step "在 API 调试台左侧找到「消息」→「发送消息」接口。"
step "确认调试台当前使用的应用是「sub2obsidian 收件箱」。"
step "在「查询参数」页签把 ID 类型设为 open_id，点击「快速复制 open_id」。"
step "在弹窗中搜索并选择你自己，点击「复制成员 ID」。"
ask FEISHU_OPEN_ID "粘贴你的 open_id（以 ou_ 开头）："
while [[ ! "$FEISHU_OPEN_ID" =~ ^ou_ ]]; do
  warn "open_id 应以 ou_ 开头，请重新复制。"
  ask FEISHU_OPEN_ID "粘贴你的 open_id："
done
write_env FEISHU_OPEN_ID "$FEISHU_OPEN_ID"

# ── 7 ────────────────────────────────────────────────────────────────────
stage "连接收件箱"
say "首次运行 sub2obsidian sync 时，机器人会在飞书里给你发一条「收件箱已连接」，"
say "这个私聊就是收件箱。之后在手机上把 B站、公众号等的分享链接发到这里，"
say "回到电脑运行 sub2obsidian sync 即可采集。"
if command -v sub2obsidian >/dev/null 2>&1; then
  if confirm "现在运行一次 sub2obsidian sync？"; then
    sub2obsidian sync || SKIPPED+=("sub2obsidian sync 没有成功：按上面的提示处理后再运行")
  else
    SKIPPED+=("运行 sub2obsidian sync，确认飞书里收到「收件箱已连接」")
  fi
else
  SKIPPED+=("安装 sub2obsidian（见 README）后运行 sub2obsidian sync，确认飞书里收到「收件箱已连接」")
fi
pause "按回车查看汇总"

finish
